### ISSUE TITLE
[BUG] <title>AttributeError: 'Qwen2ForCausalLM' object has no attribute 'chat'

### ISSUE THREAD

**Issue by lishu2006ll** [QwenLM/Qwen1.5#185] opened 2024-03-19 06:08 UTC
### 是否已有关于该错误的issue或讨论？ | Is there an existing issue / discussion for this?

- [X] 我已经搜索过已有的issues和讨论 | I have searched the existing issues / discussions

### 该问题是否在FAQ中有解答？ | Is there an existing answer for this in FAQ?

- [X] 我已经搜索过FAQ | I have searched FAQ

### 当前行为 | Current Behavior

使用docker部署qwen1.5，测试模型回答问题的时候报错：AttributeError: 'Qwen2ForCausalLM' object has no attribute 'chat'
<img width="1119" alt="image" src="https://github.com/QwenLM/Qwen/assets/3477402/e3706f79-1314-4ffc-b6be-bc64e7923286">

### 期望行为 | Expected Behavior

正常回答

### 复现方法 | Steps To Reproduce

<img width="1056" alt="image" src="https://github.com/QwenLM/Qwen/assets/3477402/ad7f0c74-d884-44f0-bc16-eab7ff062572">

### 运行环境 | Environment

```Markdown
- OS:
- Python:
- Transformers:
- PyTorch: 
- CUDA 11.7 (`python -c 'import torch; print(torch.version.cuda)'`):
```

**Comment by njhouse365** [comment] 2024-04-03 02:53
me too

**Comment by jklj077** [comment] 2024-04-16 03:18
Closed as duplicate of <https://github.com/QwenLM/Qwen1.5/issues/7>.

**Closed by jklj077** 2024-04-16 03:18 UTC
