### ISSUE TITLE
qwen1.5-7b推理报错chat_stream

### ISSUE THREAD

**Issue by wxchjay** [QwenLM/Qwen1.5#92] opened 2024-02-27 07:02 UTC
系统环境：
windows 10
显卡：3090
模型7B
torch                         2.1.0+cu121
torchaudio                    2.1.0+cu121
torchvision                   0.16.0+cu121
transformers                  4.38.1
在推理的时候报错
Traceback (most recent call last):
  File "cli_demo.py", line 200, in <module>
    main()
  File "cli_demo.py", line 188, in main
    for response in model.chat_stream(tokenizer, query, history=history, generation_config=config):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\torch\nn\modules\module.py", line 1695, in __getattr__
    raise AttributeError(f"'{type(self).__name__}' object has no attribute '{name}'")
AttributeError: 'Qwen2ForCausalLM' object has no attribute 'chat_stream
![图片](https://github.com/QwenLM/Qwen1.5/assets/150489977/62790140-3fa8-4447-96c5-59dcfefdcda5)

**Comment by jklj077** [comment] 2024-03-11 12:55
closed as duplicate of https://github.com/QwenLM/Qwen1.5/issues/38

**Closed by jklj077** 2024-03-11 12:55 UTC
