### ISSUE TITLE
💡 [REQUEST] - qwen1.5 110b能提供一个8bit量化的版本么

### ISSUE THREAD

**Issue by starsliao** [QwenLM/Qwen1.5#383] opened 2024-05-07 08:36 UTC
### 摘要 | Summary

1

### 基本示例 | Basic Example

1

### 缺陷 | Drawbacks

1

**Comment by jklj077** [comment] 2024-05-07 12:51
Closed as duplicate of https://github.com/QwenLM/Qwen1.5/issues/375

**Closed** 2024-05-21 07:41 UTC
Labels: question
